### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by amzamzamzamz** [kerberos-io/docker#16]
Docker container running, but on web page this error:
Whoops, looks like something went wrong.
'latest' build. and 'linux-amd64' too

**Comment by cedricve** [comment]
hey @amzamzamzamz, which image are you using?

**Comment by amzamzamzamz** [comment]
https://hub.docker.com/r/kerberos/kerberos/
linux-amd64 and latest

**Comment by amzamzamzamz** [comment]
Running into OpenMediaVault Docker plugin

**Comment by cedricve** [comment]
hmm, tried to run latest version and works like a charm. Are you using any special options?

**Comment by khiles** [comment]
I am same running on OMV and get same error

**Comment by cedricve** [comment]
@khiles can you provide me the web logs? /var/www/web/storage/logs M

**Comment by ChriZathens** [comment]
Hello.
Old issue I know
Just installed myself in Openmediavault and got the exact same error
Port 80 is changed to 8088

I have no logs in /var/www/web/storage/logs
Container has the following paths configured:
/etc/opt/kerberosio/logs
/var/www/web/config
/etc/opt/kerberosio/capture
/etc/opt/kerberosio/config

 which all point to different folders on my storage

The only folder that has actually populated something since the container started is /etc/opt/kerberosio/logs

It created a file log.stash and it is full of the following:

> 01/04/2020 21:28:38.086 INFO  [trivial] Logging is written to: /etc/opt/kerberosio/logs/log.stash
> 01/04/2020 21:28:38.087 INFO  [trivial] Reading configuration file: /etc/opt/kerberosio/config/config.xml
> 01/04/2020 21:28:38.087 ERROR [trivial] TinyXML : could not open the xml file, maybe the file doesn't exist?
> 

Are there any env vars that need to be passed and I am missing (did not see anything in the docker hub page, though, just the ports

**Comment by cedricve** [comment]
hey @ChriZathens can you share what is in your config folder?

**Comment by ChriZathens** [comment]
Hello
I will validate this when I get home in about 2 hours, but I am pretty sure that there was nothing created in the config folder

**Comment by cedricve** [comment]
@ChriZathens your issue is related to this one: https://github.com/kerberos-io/docker/issues/22.
We will fix this in the upcoming days. Hold on.

**Comment by ChriZathens** [comment]
Nice, thanks!

**Comment by cedricve** [comment]
We have added a fix for this #22, and are rebuilding the image. Let you know when ready.
